apiVersion: v1
kind: ConfigMap
metadata: 
  name: {{ .Release.Name }}-configmap
  labels: 
  {{- with .Values.tags }}
    first: {{ .machine }}
   second: {{ .rack }}
  third: {{ .drive }}
  {{- end }}
data: 
  myvalue: "Sample config map"
  costCode: {{ .Values.costCode }}
  zone: {{ quote .Values.infra.zone }}
  region: {{ quote .Values.infra.region }}
  projectCode: {{ upper .Values.projectCode }}
  pipeline: {{ .Values.projectCode | upper | quote }}
  now: {{ now | date "2006-01-02" | quote }}
  contact: {{ .Values.contact | default "1-800-123-0000" | quote }}
  {{- if eq .Values.infra.region "us-east" }}
  ha: true 
  {{- end }}
  {{- with .Values.tags }}
  Machine Type: {{ .machine | default "NA" | quote }}
  Rack ID: {{ .rack | quote }}
  Storage Type: {{ .drive | upper | quote }}
  Video Card: {{ .vcard | quote }}
  {{- end }}
  Land Used: |-
   {{- range .Values.LangUsed }}
   - {{ . | title | quote }}
   {{- end }}  
  